#!/bin/sh

echo "{deps,
 [{cowboy, \"\",
   {git, \"https://github.com/extend/cowboy.git\",
    {tag, \"$1\"}}}]}." > rebar.tmp.config
rebar -C rebar.tmp.config get-deps compile
cp deps/cowboy/examples/rest_hello_world/src/toppage_handler.erl test/
rebar -C rebar.tmp.config skip_deps=true ct
rebar -C rebar.tmp.config delete-deps
rm -f rebar.tmp.config
